// Generated by scripts/sync-markdown.mjs - DO NOT EDIT MANUALLY
import { BookBibliography } from "@/types/book";
import { biblio_2_corinthians } from "@/data/books/2-corinthians";

export const allBibliographies: BookBibliography[] = [biblio_2_corinthians];

export function getBookBibliography(slug: string): BookBibliography | undefined {
  return allBibliographies.find((b) => b.slug === slug);
}

export function getAllBookBibliographies(): BookBibliography[] {
  return allBibliographies;
}
